package com.travila.achievementhunt;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public class TaskContainer {
    public static ItemStack[] StartTasks = {
            new ItemStack(Material.DIRT, 24),
            new ItemStack(Material.SAND, 5),
            new ItemStack(Material.LADDER, 3),
            new ItemStack(Material.COBBLESTONE, 10),
            new ItemStack(Material.STONE_HOE, 1),
            new ItemStack(Material.FURNACE, 1),
            new ItemStack(Material.STICK, 16),
            new ItemStack(Material.WHEAT_SEEDS, 3),
            new ItemStack(Material.BOWL, 8),
            new ItemStack(Material.STONE, 1),
            new ItemStack(Material.LEVER, 4),
            new ItemStack(Material.STONE_SWORD, 1),
            new ItemStack(Material.STONE_AXE, 1),
            new ItemStack(Material.STONE_SHOVEL, 1),
            new ItemStack(Material.STRIPPED_OAK_LOG, 1),
            new ItemStack(Material.OAK_BOAT, 1),
            new ItemStack(Material.OAK_DOOR, 3),
            new ItemStack(Material.CRAFTING_TABLE, 3),
    };
    public static ItemStack[] EasyTasks = {
            new ItemStack(Material.COAL, 5),
            new ItemStack(Material.IRON_INGOT, 2),
            new ItemStack(Material.CHARCOAL, 8),
            new ItemStack(Material.GRINDSTONE, 1),
            new ItemStack(Material.FLETCHING_TABLE, 1),
            new ItemStack(Material.POLISHED_ANDESITE, 4),
            new ItemStack(Material.SHIELD, 1),
            new ItemStack(Material.ARROW, 4),
            new ItemStack(Material.ARMOR_STAND, 1),
            new ItemStack(Material.POPPY, 3),
            new ItemStack(Material.RED_WOOL, 1),
            new ItemStack(Material.TORCH, 4),
            new ItemStack(Material.LANTERN, 1),
            new ItemStack(Material.CAMPFIRE, 1),
            new ItemStack(Material.PAINTING, 1),
            new ItemStack(Material.TRAPPED_CHEST, 1),
            new ItemStack(Material.SMOKER, 1),
            new ItemStack(Material.GLASS, 6),
    };
    public static ItemStack[] MediumTasks = {
            new ItemStack(Material.RAIL, 16),
            new ItemStack(Material.PAPER, 6),
            new ItemStack(Material.BONE_BLOCK, 1),
            new ItemStack(Material.IRON_CHESTPLATE, 1),
            new ItemStack(Material.FLINT_AND_STEEL, 1),
            new ItemStack(Material.WATER_BUCKET, 1),
            new ItemStack(Material.ORANGE_BED, 1),
            new ItemStack(Material.PINK_BED, 1),
            new ItemStack(Material.BLACK_BED, 1),
            new ItemStack(Material.YELLOW_CARPET, 6),
            new ItemStack(Material.PORKCHOP, 3),
            new ItemStack(Material.OAK_DOOR, 6),
            new ItemStack(Material.BIRCH_DOOR, 6),
            new ItemStack(Material.STONE_BUTTON, 16),
            new ItemStack(Material.LEATHER, 2),
            new ItemStack(Material.LEATHER_HELMET, 1),
            new ItemStack(Material.OAK_LEAVES, 16),
            new ItemStack(Material.BIRCH_LEAVES, 16),
            new ItemStack(Material.ITEM_FRAME, 4),
            new ItemStack(Material.SANDSTONE_STAIRS, 8),
            new ItemStack(Material.RED_CONCRETE, 8),
            new ItemStack(Material.YELLOW_CONCRETE, 8),
            new ItemStack(Material.FLOWER_POT, 4),
            new ItemStack(Material.BOW, 1),
            new ItemStack(Material.MILK_BUCKET, 1),
            new ItemStack(Material.FISHING_ROD, 1),
            new ItemStack(Material.IRON_AXE, 1),
    };
    public static ItemStack[] HardTasks = {
            new ItemStack(Material.BOOKSHELF, 1),
            new ItemStack(Material.LECTERN, 1),
            new ItemStack(Material.WHEAT, 2),
            new ItemStack(Material.COMPASS, 1),
            new ItemStack(Material.BRICKS, 8),
            new ItemStack(Material.FLOWER_POT, 1),
            new ItemStack(Material.REDSTONE_BLOCK, 1),
            new ItemStack(Material.BONE_BLOCK, 1),
            new ItemStack(Material.ROTTEN_FLESH, 6),
            new ItemStack(Material.GUNPOWDER, 2),
            new ItemStack(Material.SALMON, 2),
            new ItemStack(Material.REPEATER, 1),
            new ItemStack(Material.BLAST_FURNACE, 1),
            new ItemStack(Material.BLACK_STAINED_GLASS, 16),
            new ItemStack(Material.ORANGE_STAINED_GLASS, 16),
            new ItemStack(Material.PINK_STAINED_GLASS, 16),
            new ItemStack(Material.CAULDRON, 1),
            new ItemStack(Material.NOTE_BLOCK, 4),
            new ItemStack(Material.PISTON, 2),
            new ItemStack(Material.WRITABLE_BOOK, 1),
            new ItemStack(Material.CROSSBOW, 1),
    };
    public static ItemStack[] ExtremeTasks = {
            new ItemStack(Material.COMPASS, 2),
            new ItemStack(Material.CLOCK, 1),
            new ItemStack(Material.TNT, 1),
            new ItemStack(Material.TNT_MINECART, 1),
            new ItemStack(Material.GOLDEN_APPLE, 1),
            new ItemStack(Material.ANVIL, 1),
            new ItemStack(Material.LAPIS_BLOCK, 2),
            new ItemStack(Material.DISPENSER, 2),
            new ItemStack(Material.ENDER_PEARL, 3),
            new ItemStack(Material.LIGHT_WEIGHTED_PRESSURE_PLATE, 3),
            new ItemStack(Material.POWERED_RAIL, 6),
            new ItemStack(Material.PUFFERFISH, 1),
            new ItemStack(Material.RABBIT_FOOT, 1),
            new ItemStack(Material.FERMENTED_SPIDER_EYE, 3),
            new ItemStack(Material.MUSHROOM_STEW, 1),
            new ItemStack(Material.DRIED_KELP_BLOCK, 1),
            new ItemStack(Material.RED_GLAZED_TERRACOTTA, 1),
            new ItemStack(Material.YELLOW_GLAZED_TERRACOTTA, 1),
            new ItemStack(Material.NETHERRACK, 12),
            new ItemStack(Material.MAGMA_BLOCK, 2),
            new ItemStack(Material.TARGET, 1),
    };
    public static ItemStack[] ImpossibleTasks = {
            new ItemStack(Material.DIAMOND_AXE, 1),
            new ItemStack(Material.DIAMOND_BOOTS, 1),
            new ItemStack(Material.WARPED_FUNGUS_ON_A_STICK, 1),
            new ItemStack(Material.CAKE, 1),
            new ItemStack(Material.SOUL_LANTERN, 1),
            new ItemStack(Material.JUKEBOX, 2),
            new ItemStack(Material.SOUL_CAMPFIRE, 1),
            new ItemStack(Material.RABBIT_STEW, 1),
            new ItemStack(Material.EMERALD, 3),
            new ItemStack(Material.DAMAGED_ANVIL, 2),
            new ItemStack(Material.BELL, 1),
            new ItemStack(Material.QUARTZ_STAIRS, 8),
            new ItemStack(Material.GLOWSTONE, 4),
            new ItemStack(Material.DAYLIGHT_DETECTOR, 2),
            new ItemStack(Material.SPECTRAL_ARROW, 4),
    };
    public static ItemStack[] EndgameTasks = {
            new ItemStack(Material.SPLASH_POTION, 1),
            new ItemStack(Material.NETHER_WART, 32),
            new ItemStack(Material.ENCHANTING_TABLE, 1),
            new ItemStack(Material.GHAST_TEAR, 3),
            new ItemStack(Material.DIAMOND_BLOCK, 1),
            new ItemStack(Material.EMERALD_BLOCK, 3),
            new ItemStack(Material.GOLD_BLOCK, 6),
            new ItemStack(Material.SADDLE, 1),
            new ItemStack(Material.GLISTERING_MELON_SLICE, 2),
            new ItemStack(Material.PUFFERFISH_BUCKET, 1),
            new ItemStack(Material.HEART_OF_THE_SEA, 1),
            new ItemStack(Material.NAUTILUS_SHELL, 1),
    };
}
